<a href="https://colab.research.google.com/github/together0/pytorch/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch 
from torch import autograd
print(torch.__version__)

1.7.0+cu101


梯度


In [4]:
x = torch.tensor(1.)
a = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(2.0, requires_grad=True)
c = torch.tensor(3.0, requires_grad=True)
y = a**2*x + b*x + c
grads = autograd.grad(y, [a, b, c])
print(grads)

(tensor(2.), tensor(1.), tensor(1.))


张量的类型、类型比较、形状、尺寸

In [9]:
data = torch.tensor(1.0)
isinstance(data, torch.FloatTensor)

True

In [8]:
data.type()

'torch.FloatTensor'

In [10]:
data = data.cuda()
isinstance(data, torch.cuda.FloatTensor)

True

In [11]:
data.type()

'torch.cuda.FloatTensor'

In [13]:
print(data.shape)
print(data.size())

torch.Size([])
torch.Size([])


张量

In [17]:
import numpy as np
# 0维 / 一维tensor
data = torch.tensor(1.0)  # 0维度
print(data)
data = torch.tensor([1.0, 2.0])
print(data)
data = torch.FloatTensor(2)  
print(data)
data = np.ones(2)
print(data)
print(type(data))
data = torch.from_numpy(data)
print(data)

tensor(1.)
tensor([1., 2.])
tensor([-1.5345e-32,  0.0000e+00])
[1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1.], dtype=torch.float64)


In [26]:
# 二维tensor
data = torch.randn(2, 3)  # 正态分布
print(data)
print(data.shape)
print(data.shape[1])
print(data[0])

tensor([[-5.8778e-01,  3.2835e-04,  1.0556e+00],
        [-6.5604e-01, -3.1196e-02, -1.6146e+00]])
torch.Size([2, 3])
3
tensor([-5.8778e-01,  3.2835e-04,  1.0556e+00])


In [27]:
# 三维tensor
data = torch.rand(1,2,3)  # 0-1随机分布
print(data)
print(data.shape)
print(data.shape[2])
print(data[0][0])

tensor([[[0.3608, 0.7631, 0.0061],
         [0.6710, 0.3250, 0.6428]]])
torch.Size([1, 2, 3])
3
tensor([0.3608, 0.7631, 0.0061])


In [30]:
# 四维tensor
data = torch.rand(2,3,28,28)
print(data.shape)

torch.Size([2, 3, 28, 28])


In [32]:
# tensor的情况
count = data.numel()
print(count)
dimension = data.dim()
print(dimension)

4704
4


In [44]:
# 使用list或者ndarray类型进行转换
data = torch.tensor([111,222])
print(data)
print(data.type())
data = torch.FloatTensor([111,222])
print(data)
print(data.type())
data = torch.FloatTensor(2, 3)
print(data)
print(data.type())
data = data.cuda()
print(data.type())
data = torch.tensor([[100,200],[300,400]])
print(data)
print(data.shape)

tensor([111, 222])
torch.LongTensor
tensor([111., 222.])
torch.FloatTensor
tensor([[-1.5337e-32,  0.0000e+00,  5.9445e-01],
        [ 6.4460e-44,  5.9445e-01,  5.9445e-01]])
torch.FloatTensor
torch.cuda.FloatTensor
tensor([[100, 200],
        [300, 400]])
torch.Size([2, 2])


In [46]:
# 定义时不初始化
data = torch.empty(2,3)
torch.IntTensor()
torch.FloatTensor()
print(data)

tensor([[-1.5337e-32,  0.0000e+00,  1.5975e-43],
        [ 1.3873e-43,  1.4574e-43,  6.4460e-44]])


In [48]:
# 设置tensor的默认数据类型
data = torch.Tensor([1.1, 2.2])
print(data.type())
torch.set_default_tensor_type(torch.DoubleTensor)
data = torch.Tensor([1.1, 2.2])
print(data.type())

torch.DoubleTensor
torch.DoubleTensor


In [62]:
# 随机初始化
data = torch.rand(3,3)  # 0-1随机分布
print(data)
data = torch.rand_like(data)  # 根据data的shape，调用torch.rand()
print(data)
data = torch.randint(1, 10, [3,3])  # 给定范围[min, max)随机分布
print(data)
data = torch.randn(3,3)  # 正态分布
print(data)
data = torch.normal(mean=torch.full([10],0.0), std=torch.full([10], 2))
print(data)
data = torch.normal(mean=torch.full([10],0.0), std=torch.arange(1, 0, -0.1))
print(data)
data = torch.full([2,3] ,2.2)  # 全部赋值为同一个值
print(data)
print(data.type())
data = torch.arange(0,10)  # 递增或者递减
print(data)
data = torch.arange(0,10,2)  # 第三个参数是步长
print(data)
data = torch.linspace(1,10,3)  # 等分，第三个参数是个数
print(data)
data = torch.ones(3,3)
data = torch.zeros(3,3)
data = torch.eye(3) # 单位矩阵

tensor([[0.5623, 0.6637, 0.2372],
        [0.3312, 0.8855, 0.4786],
        [0.6465, 0.7086, 0.7587]])
tensor([[0.8938, 0.3718, 0.5704],
        [0.6285, 0.6486, 0.7970],
        [0.2873, 0.8220, 0.3745]])
tensor([[5, 3, 8],
        [4, 9, 9],
        [5, 6, 1]])
tensor([[ 1.1283,  1.1035,  1.9102],
        [-0.8133, -0.6443,  0.2601],
        [-0.1349, -0.9156, -1.6049]])
tensor([ 2.8697, -0.7291,  0.0699, -0.2482,  0.2753,  1.1102, -3.2818, -3.3665,
        -0.2564,  3.3131])
tensor([-0.2411, -0.1712,  0.8331, -0.2664,  0.3636, -0.6080,  0.0844, -0.1840,
         0.0652, -0.1660])
tensor([[2.2000, 2.2000, 2.2000],
        [2.2000, 2.2000, 2.2000]])
torch.DoubleTensor
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 1.0000,  5.5000, 10.0000])


In [72]:
# 拼接与拆分
class_1 = torch.rand(3,40,6)
class_2 = torch.rand(4,40,6)
class_1_2 = torch.cat([class_1,class_2], dim=0)  # dim: 沿着哪个维度进行合并
print(class_1_2.shape)

# stack会形成一个新的维度
class_1 = torch.rand(2,3)
class_2 = torch.rand(2,3)
class_cat = torch.cat([class_1, class_2])
print(class_cat)
class_stack = torch.stack([class_1, class_2])
print(class_stack)

# 分割：split，按照长度拆分
class_1,class_2 = class_stack.split(1)  # 根据长度进行分割，每3个长度分割一次。
print(class_1,class_2)

class_1 = torch.rand(2,3)
class_2 = torch.rand(4,3)
class_cat = torch.cat([class_1, class_2])
print("--------------------")
print(class_cat)
class_1, class_2 = class_cat.split([1,5])  # 指定每个部分的长度
print(class_1, class_2)

# 分割：chunk，按照个数拆分
class_1, class_2, class_3 = class_cat.chunk(3)
print("----------------------")
print(class_1, class_2, class_3)

torch.Size([7, 40, 6])
tensor([[0.6963, 0.3604, 0.5624],
        [0.4862, 0.1585, 0.6593],
        [0.4027, 0.7849, 0.8361],
        [0.3645, 0.9388, 0.3748]])
tensor([[[0.6963, 0.3604, 0.5624],
         [0.4862, 0.1585, 0.6593]],

        [[0.4027, 0.7849, 0.8361],
         [0.3645, 0.9388, 0.3748]]])
tensor([[[0.6963, 0.3604, 0.5624],
         [0.4862, 0.1585, 0.6593]]]) tensor([[[0.4027, 0.7849, 0.8361],
         [0.3645, 0.9388, 0.3748]]])
--------------------
tensor([[0.8000, 0.0349, 0.9740],
        [0.0091, 0.4742, 0.6428],
        [0.7459, 0.2898, 0.0669],
        [0.9633, 0.1412, 0.6890],
        [0.0563, 0.3241, 0.1185],
        [0.3051, 0.0840, 0.2817]])
tensor([[0.8000, 0.0349, 0.9740]]) tensor([[0.0091, 0.4742, 0.6428],
        [0.7459, 0.2898, 0.0669],
        [0.9633, 0.1412, 0.6890],
        [0.0563, 0.3241, 0.1185],
        [0.3051, 0.0840, 0.2817]])
----------------------
tensor([[0.8000, 0.0349, 0.9740],
        [0.0091, 0.4742, 0.6428]]) tensor([[0.7459, 0.2898, 0.0